baseURL = 'https://ishikawa-blog.blog/'
languageCode = 'ja-jp'
title = 'ishikawa'

relativeURLs = false
canonifyURLs = true

theme = 'hugo-nes'

[params]
    title = "（仮）タイトル"
    description = "Python、情報セキュリティ"
    author = "ishikawa"

[[menu.main]]
    name = "Home"
    pageRef = "/"
    weight = 1

[[menu.main]]
    name = "Blog"
    pageRef = "/posts"
    weight = 2

[[menu.main]]
    name = "About Me"
    pageRef = "/about"
    weight = 3

# 記事一覧の表示件数
paginate = 6

[markup.goldmark.renderer]
    unsafe = true

[taxonomies]
    tag = "tags"
    category = "categories"
